services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # painel web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  storefrontapp:
    build:
      context: .
    command: bash start-dev.sh
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8081:8081"
      - "5006:5005"
    volumes:
      - .:/storefront
    working_dir: /storefront
    depends_on:
      rabbitmq:
        condition: service_healthy